### ISSUE TITLE
What is the relation of password and secret key in getHoard? 

### ISSUE THREAD

**Issue by puneetverma05** [agreements-network/blackstone#120]
Is the secret key also salted with user's password? 

https://github.com/agreements-network/blackstone/blob/ae5b16152c2b9c821f8aa30371ddfd7194b918a2/api/controllers/hoard-controller.js#L42

**Comment by j-h-scheufen** [comment]
Hi @puneetverma05, sorry for the delay in replying!
The `password` you see being passed as a parameter to the decrypt function is used as a way to make a shareable `secretKey`. I.e. you can encrypt the secretKey with an additional password, then share the secretKey with others and provide them with the password to decrypt.
However, the secretKey can be salted at the moment when storing a file in Hoard. This is done in the hoard.put function as can be seen here: https://github.com/agreements-network/blackstone/blob/ae5b16152c2b9c821f8aa30371ddfd7194b918a2/api/controllers/hoard-controller.js#L26

See also: https://github.com/monax/hoard#encryption-scheme

I'm hopeful that this answers your question and I'll close the ticket. Let us know if there's anything else.

**Comment by puneetverma05** [comment]
So right now this is not used? In a future iteration, this password will be used for shareable secret key?
https://github.com/agreements-network/blackstone/blob/ae5b16152c2b9c821f8aa30371ddfd7194b918a2/api/controllers/hoard-controller.js#L42

**Comment by j-h-scheufen** [comment]
That is correct in terms of the default behavior. However, when someone is building an application on top of the blackstone API, the use of the shareable secret can be implemented, so it's up to the application leveraging the blackstone API to make use of it.
