### ISSUE TITLE
MakeFile Error

### ISSUE THREAD

**Issue by puneetverma05** [agreements-network/blackstone#42]
When running commands like **make run / run_all** :
No such service: Container: blackstone_postgres_1 ( Postgres container is running fine but not recognizing it)
also these files are also not found:
```
 '/app/burrow.log': No such file or directory
'/app/contracts/src/*.output.json': No such file or directory
 '/app/test*.log': No such file or directory
```

**Comment by gregdhill** [comment]
Thanks for the report @puneetverma05! Unfortunately I can't seem to reproduce the first issue locally, so would you mind reporting the `docker version` and `docker-compose version`? 

The other files you have listed as not found under `/app` are only local to the `chain` container so as part of the cleanup script through docker-compose, we remove these from a successful deployment; so you can safely ignore these warnings!

**Comment by gregdhill** [comment]
Thanks for the report @puneetverma05! Unfortunately I can't seem to reproduce the first issue locally, so would you mind reporting the `docker version` and `docker-compose version`? 

The other files you have listed as not found under `/app` are only local to the `chain` container so as part of the cleanup script through docker-compose, we remove these from a successful deployment; so you can safely ignore these warnings!

**Comment by puneetverma05** [comment]
**Docker Version:** 
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:38 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:45 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Docker Compose Version :**
```
docker-compose version 1.13.0, build 1719ceb
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

**Comment by puneetverma05** [comment]
Any updates on this?

**Comment by gregdhill** [comment]
We're still unable to replicate this bug unfortunately. Could you append more comprehensive logs of the fault in question?

**Comment by compleatang** [comment]
nobody on our end can reproduce this @puneetverma05 .

remove your docker images, pull latest blackstone code, ensure you have node_modules installed (`make install_api`) without errors, and then use `make run` rather than `make run_all`. let us know the logs if it fails.

**Comment by puneetverma05** [comment]
Error still persist , I have tried above before also so many times :( , let me try different scenarios from my end also.

**Comment by compleatang** [comment]
@puneetverma05 if it is still throwing on you then please dump us the docker logs `docker log CONTAINER_NAME`

**Comment by puneetverma05** [comment]
this is the command that is throwing the error and after that **build** container is going down
`docker-compose rm --force --stop`

**Comment by puneetverma05** [comment]
Why in  run  (line 27 , makefile)  we are calling clean ? I think the problem is with the flow of run commands , I have now tried without make file and run the docker` docker-compose run chain test/test_api.sh` command directly and it is running test cases fine.
```
.PHONY: run
run: clean
	docker-compose up -d
	docker-compose logs --follow chain &
```

**Comment by compleatang** [comment]
we run clean because it is built for rapid development. here's what i get in a completely clean docker envirnoment (e.g., no images to remove).

```
coda@coda-xenial:~/coding/gostuff/src/github.com/monax/an/blackstone [segment-fixes☿☿☿] >> make clean                                                                                                                                               [13:30:51]
pkill docker-compose || true
docker-compose run --no-deps chain test/clean
rm: cannot remove '/app/burrow.log': No such file or directory
rm: cannot remove '/app/contracts/src/*.output.json': No such file or directory
rm: cannot remove '/app/test*.log': No such file or directory
docker-compose rm --force --stop
Going to remove blackstone_chain_run_1
Removing blackstone_chain_run_1 ... done
coda@coda-xenial:~/coding/gostuff/src/github.com/monax/an/blackstone [segment-fixes☿☿☿] >> echo $?                                                                                                                                                  [13:30:56]
0
coda@coda-xenial:~/coding/gostuff/src/github.com/monax/an/blackstone [segment-fixes☿☿☿] >> docker-compose version                                                                                                                                   [13:31:00]
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by compleatang** [comment]
your docker-compose is rather old. if the `docker-py` version is indicative I'm not exactly sure it can run the docker-compose.yml which is in `version: "3"`. 

so you have two options, just run the commands without the make abstraction or upgrade your docker-compose to something more recent and retry. if the docker-compose raw commands are working for you then just use those.

**Comment by puneetverma05** [comment]
For me Problem is with clean :
```
~/workplace/blackstone$ make clean
pkill docker-compose || true
docker-compose run --no-deps chain test/clean
rm: cannot remove '/app/test*.log': No such file or directory
docker-compose rm --force --stop
ERROR: No such service: <Container: blackstone_hoard_1 (1d1a18)>
Makefile:44: recipe for target 'clean' failed
make: *** [clean] Error 1
~/workplace/blackstone$ 

```
I will be running the commands directly! :+1:

**Comment by compleatang** [comment]
coolio! glad it's working for you now and sorry about the back and forth!
